name: Node CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn

      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn tsc
      - run: yarn test
